# Generated by Django 2.0.5 on 2018-06-26 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_auto_20180626_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 23, 43, 38, 463834, tzinfo=utc), editable=False),
        ),
    ]
