# Generated by Django 2.0.5 on 2018-06-26 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_auto_20180626_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 23, 45, 53, 760838, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 23, 45, 53, 760868, tzinfo=utc)),
        ),
    ]
