# Generated by Django 2.0.5 on 2018-06-27 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0006_auto_20180626_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 25, 39, 323851, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 25, 39, 323879, tzinfo=utc)),
        ),
    ]
