# Generated by Django 2.0.5 on 2018-06-27 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0008_auto_20180626_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 32, 57, 720993, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 32, 57, 721019, tzinfo=utc)),
        ),
    ]
