# Generated by Django 2.0.5 on 2018-06-27 00:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0009_auto_20180626_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 35, 28, 263105, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 35, 28, 263135, tzinfo=utc)),
        ),
    ]
