# Generated by Django 2.0.5 on 2018-06-27 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0010_auto_20180626_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 38, 17, 52171, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 27, 0, 38, 17, 52198, tzinfo=utc)),
        ),
    ]
