# Generated by Django 2.0.5 on 2018-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0012_auto_20180626_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
