# Generated by Django 2.0.5 on 2018-06-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0013_auto_20180626_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
