# Generated by Django 2.0.5 on 2018-07-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0016_auto_20180713_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digest',
            field=models.SlugField(null=True),
        ),
    ]
