# Generated by Django 2.0.5 on 2018-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0016_auto_20180713_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_id',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
