# Generated by Django 2.0.5 on 2018-07-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0017_user_activation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_id',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
