# Generated by Django 2.0.5 on 2018-07-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0018_user_password_change_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_change_id',
        ),
    ]
