# Generated by Django 2.0.5 on 2018-07-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0021_auto_20180720_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='micropost_pictures'),
        ),
    ]
