# Generated by Django 2.0.5 on 2018-07-24 20:27

from django.db import migrations, models
import static_pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0022_micropost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=static_pages.models.image_file_path),
        ),
    ]
