# Generated by Django 2.0.5 on 2018-07-31 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0023_auto_20180724_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
